### ISSUE TITLE
QUESTION: Acquiring multiple locks

### ISSUE THREAD

**Issue by bobsquito** [AmrSaber/simple-redis-mutex#11]
Hi,
I'm not clever enough to figure this out, so I just wanted to check.

I am wanting to acquire a lock while updating multiple resources, so ideally I would want to get a lock for each resource. I am assuming that there will be 1 call to redis for each lock, so if I wanted to lock 500 resources, then that would be 500 calls to redis which would probably cause some problem. I guess there is no way to group calls to get several locks at once?

Thanks

**Comment by AmrSaber** [comment]
Hello Rob, thank you for reaching out!

As I understand your situation, you need to lock 500 resources for a task you are doing. There could be 2 cases here...

### Case 1 - All of 500 resources are dependencies for 1 task
All these task are related, and you MUST lock them all together; i.e. 1 lock operation must **wait for all of them** (500 dependency can be a lot of waiting) to be locked before proceeding.

I would assume also that these resources are individually shared with other operations, so you cannot use 1 lock for the whole operation itself, is that right?

If this is the case, then I would be happy to add a new `batchLock` functionality to support this case.

### Case 2 - You are doing some task that involves updating 500 different independent resources
All these tasks are not related, and each one of them can run separately of the others, but the operation you're doing involves updating all of these tasks.

In this case it would be better to acquire a separate lock for each operation to reduce the total waiting time, even if they are 500 resources, acquiring a lock is as simple as setting 1 value in Redis, and Redis is REALLY fast (it can do **74_239.05** set operations per second -- see [their benchmark here](https://redis.io/docs/management/optimization/benchmarks/))

---

So which one is your case?

**Comment by AmrSaber** [comment]
Closing this as inactive
